<?php

namespace App\Listeners;
use Illuminate\Auth\Events\Authenticated;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Queue\InteractsWithQueue;
use Spatie\Permission\Models\Permission;

class CreatePermissionsOnLogin
{
    /**
     * Create the event listener.
     *
     * @return void
     */
    public function __construct()
    {
        //
    }

    /**
     * Handle the event.
     *
     * @param  object  $event
     * @return void
     */
    public function handle(Authenticated $event)
    {
        $permisos = [
            "inicio",
            "transacciones",
            "transacciones-ventas",
            "transacciones-ventas-cotizaciones.index",
            "transacciones-ventas-cotizaciones.create",
            "transacciones-ventas-cotizaciones.store",
            "transacciones-ventas-cotizaciones.show",
            "transacciones-ventas-cotizaciones.edit",
            "transacciones-ventas-cotizaciones.update",
            "transacciones-ventas-cotizaciones.destroy",
            "transacciones-ventas-facturacion.index",
            "transacciones-ventas-facturacion.create",
            "transacciones-ventas-facturacion.store",
            "transacciones-ventas-facturacion.show",
            "transacciones-ventas-facturacion.edit",
            "transacciones-ventas-facturacion.update",
            "transacciones-ventas-facturacion.destroy",
            "transacciones-ventas-boleta.index",
            "transacciones-ventas-boleta.create",
            "transacciones-ventas-boleta.store",
            "transacciones-ventas-boleta.show",
            "transacciones-ventas-boleta.edit",
            "transacciones-ventas-boleta.update",
            "transacciones-ventas-boleta.destroy",
            "transacciones-ventas-guia_remision.index",
            "transacciones-ventas-guia_remision.create",
            "transacciones-ventas-guia_remision.store",
            "transacciones-ventas-guia_remision.show",
            "transacciones-ventas-guia_remision.edit",
            "transacciones-ventas-guia_remision.update",
            "transacciones-ventas-guia_remision.destroy",
            "transacciones-garantias",
            "transacciones-garantias-guias_ingreso.index",
            "transacciones-garantias-guias_ingreso.create",
            "transacciones-garantias-guias_ingreso.store",
            "transacciones-garantias-guias_ingreso.show",
            "transacciones-garantias-guias_ingreso.edit",
            "transacciones-garantias-guias_ingreso.update",
            "transacciones-garantias-guias_ingreso.destroy",
            "transacciones-garantias-guias_egreso.index",
            "transacciones-garantias-guias_egreso.create",
            "transacciones-garantias-guias_egreso.store",
            "transacciones-garantias-guias_egreso.show",
            "transacciones-garantias-guias_egreso.edit",
            "transacciones-garantias-guias_egreso.update",
            "transacciones-garantias-guias_egreso.destroy",
            "transacciones-garantias-informe_tecnico.index",
            "transacciones-garantias-informe_tecnico.create",
            "transacciones-garantias-informe_tecnico.store",
            "transacciones-garantias-informe_tecnico.show",
            "transacciones-garantias-informe_tecnico.edit",
            "transacciones-garantias-informe_tecnico.update",
            "transacciones-garantias-informe_tecnico.destroy",
            "inventario",
            "inventario-productos_kardex",
            "inventario-productos_kardex-entrada_producto.index",
            "inventario-productos_kardex-entrada_producto.create",
            "inventario-productos_kardex-entrada_producto.store",
            "inventario-productos_kardex-entrada_producto.show",
            "inventario-productos_kardex-entrada_producto.edit",
            "inventario-productos_kardex-entrada_producto.update",
            "inventario-productos_kardex-entrada_producto.destroy",
            "inventario-productos_kardex-salida_producto.index",
            "inventario-productos_kardex-salida_producto.create",
            "inventario-productos_kardex-salida_producto.store",
            "inventario-productos_kardex-salida_producto.show",
            "inventario-productos_kardex-salida_producto.edit",
            "inventario-productos_kardex-salida_producto.update",
            "inventario-productos_kardex-salida_producto.destroy",
            "inventario-productos-inventario_inicial.index",
            "inventario-productos-inventario_inicial.create",
            "inventario-productos-inventario_inicial.store",
            "inventario-productos-inventario_inicial.show",
            "inventario-productos-inventario_inicial.edit",
            "inventario-productos-inventario_inicial.update",
            "inventario-productos-inventario_inicial.destroy",
            "inventario-toma_de_inventario.index",
            "inventario-toma_de_inventario.create",
            "inventario-toma_de_inventario.store",
            "inventario-toma_de_inventario.show",
            "inventario-toma_de_inventario.edit",
            "inventario-toma_de_inventario.update",
            "inventario-toma_de_inventario.destroy",
            "planilla",
            "planilla-datos_generales.index",
            "planilla-datos_generales.create",
            "planilla-datos_generales.store",
            "planilla-datos_generales.show",
            "planilla-datos_generales.edit",
            "planilla-datos_generales.update",
            "planilla-datos_generales.destroy",
            "planilla-vendedores.index",
            "planilla-vendedores.create",
            "planilla-vendedores.store",
            "planilla-vendedores.show",
            "planilla-vendedores.edit",
            "planilla-vendedores.update",
            "planilla-vendedores.destroy",
            "consultas",
            "consultas-garantias",
            "consultas-garantias-guia_ingreso.index",
            "consultas-garantias-guia_ingreso.create",
            "consultas-garantias-guia_ingreso.store",
            "consultas-garantias-guia_ingreso.show",
            "consultas-garantias-guia_ingreso.edit",
            "consultas-garantias-guia_ingreso.update",
            "consultas-garantias-guia_ingreso.destroy",
            "consultas-garantias-guia_egreso.index",
            "consultas-garantias-guia_egreso.create",
            "consultas-garantias-guia_egreso.store",
            "consultas-garantias-guia_egreso.show",
            "consultas-garantias-guia_egreso.edit",
            "consultas-garantias-guia_egreso.update",
            "consultas-garantias-guia_egreso.destroy",
            "consultas-garantias-informe_tecnico.index",
            "consultas-garantias-informe_tecnico.create",
            "consultas-garantias-informe_tecnico.store",
            "consultas-garantias-informe_tecnico.show",
            "consultas-garantias-informe_tecnico.edit",
            "consultas-garantias-informe_tecnico.update",
            "consultas-garantias-informe_tecnico.destroy",
            "auxiliares",
            "auxiliares-clientes.index",
            "auxiliares-clientes.create",
            "auxiliares-clientes.store",
            "auxiliares-clientes.show",
            "auxiliares-clientes.edit",
            "auxiliares-clientes.update",
            "auxiliares-clientes.destroy",
            "auxiliares-provedores.index",
            "auxiliares-provedores.create",
            "auxiliares-provedores.store",
            "auxiliares-provedores.show",
            "auxiliares-provedores.edit",
            "auxiliares-provedores.update",
            "auxiliares-provedores.destroy",
            'maestro',
            'maestro-catalogo',
            'maestro-catalogo-productos.index',
            'maestro-catalogo-productos.create',
            'maestro-catalogo-productos.store',
            'maestro-catalogo-productos.show',
            'maestro-catalogo-productos.edit',
            'maestro-catalogo-productos.update',
            'maestro-catalogo-productos.destroy',
            'maestro-catalogo-clasificacion',
            'maestro-catalogo-clasificacion-categorias.index',
            'maestro-catalogo-clasificacion-categorias.create',
            'maestro-catalogo-clasificacion-categorias.store',
            'maestro-catalogo-clasificacion-categorias.show',
            'maestro-catalogo-clasificacion-categorias.edit',
            'maestro-catalogo-clasificacion-categorias.update',
            'maestro-catalogo-clasificacion-categorias.destroy',
            'maestro-catalogo-clasificacion-familias.index',
            'maestro-catalogo-clasificacion-familias.create',
            'maestro-catalogo-clasificacion-familias.store',
            'maestro-catalogo-clasificacion-familias.show',
            'maestro-catalogo-clasificacion-familias.edit',
            'maestro-catalogo-clasificacion-familias.update',
            'maestro-catalogo-clasificacion-familias.destroy',
            'maestro-catalogo-clasificacion-marcas.index',
            'maestro-catalogo-clasificacion-marcas.create',
            'maestro-catalogo-clasificacion-marcas.store',
            'maestro-catalogo-clasificacion-marcas.show',
            'maestro-catalogo-clasificacion-marcas.edit',
            'maestro-catalogo-clasificacion-marcas.update',
            'maestro-catalogo-clasificacion-marcas.destroy',
            'maestro-tablas_generales',
            'maestro-tablas_generales-motivos.index',
            'maestro-tablas_generales-motivos.create',
            'maestro-tablas_generales-motivos.store',
            'maestro-tablas_generales-motivos.show',
            'maestro-tablas_generales-motivos.edit',
            'maestro-tablas_generales-motivos.update',
            'maestro-tablas_generales-motivos.destroy',
            'maestro-almacenes.index',
            'maestro-almacenes.create',
            'maestro-almacenes.store',
            'maestro-almacenes.show',
            'maestro-almacenes.edit',
            'maestro-almacenes.update',
            'maestro-almacenes.destroy',
            'maestro-usuarios.index',
            'maestro-usuarios.create',
            'maestro-usuarios.store',
            'maestro-usuarios.show',
            'maestro-usuarios.edit',
            'maestro-usuarios.update',
            'maestro-usuarios.destroy',
            'maestro-monedas.index',
            'maestro-monedas.create',
            'maestro-monedas.store',
            'maestro-monedas.show',
            'maestro-monedas.edit',
            'maestro-monedas.update',
            'maestro-monedas.destroy',
            'maestro-tipo_de_cambio.index',
            'maestro-tipo_de_cambio.create',
            'maestro-tipo_de_cambio.store',
            'maestro-tipo_de_cambio.show',
            'maestro-tipo_de_cambio.edit',
            'maestro-tipo_de_cambio.update',
            'maestro-tipo_de_cambio.destroy',
            'maestro-configuracion_general',
            'maestro-configuracion_general.mi_empresa.index',
            'maestro-configuracion_general.mi_empresa.create',
            'maestro-configuracion_general.mi_empresa.store',
            'maestro-configuracion_general.mi_empresa.show',
            'maestro-configuracion_general.mi_empresa.edit',
            'maestro-configuracion_general.mi_empresa.update',
            'maestro-configuracion_general.mi_empresa.destroy',
            'maestro-configuracion_general.unidad_de_medida.index',
            'maestro-configuracion_general.unidad_de_medida.create',
            'maestro-configuracion_general.unidad_de_medida.store',
            'maestro-configuracion_general.unidad_de_medida.show',
            'maestro-configuracion_general.unidad_de_medida.edit',
            'maestro-configuracion_general.unidad_de_medida.update',
            'maestro-configuracion_general.unidad_de_medida.destroy',
            'maestro-configuracion_general.igv.index',
            'maestro-configuracion_general.igv.create',
            'maestro-configuracion_general.igv.store',
            'maestro-configuracion_general.igv.show',
            'maestro-configuracion_general.igv.edit',
            'maestro-configuracion_general.igv.update',
            'maestro-configuracion_general.igv.destroy',
            //permisos generales para administrador y colaborador
            'admin-access',
            'colaborador-access',
            
        ];

        //agregar todos los permisos al administrador

        foreach ($permisos as $permiso) {
            $existingPermission = Permission::where("name", $permiso)->first();
            if (!$existingPermission) {
                Permission::create(['name' => $permiso]);
            }
        }

    }
}
